module.exports = {
    "val1": "",
    "val2": "",
    "val3": "",
    "val4": "",
    "val5": "",
    "val6": "",
    "val7": "",
    "val8": "",
    "val9": "",
    "val10": "",
    "val11": "",
    "val12": "",
    "val13": "",
    "val14": "",
    "val15": "",
    "val16": "",
    "val17": "",
    "val18": "",
    "val19": "",
    "val20": "",
    "val21": "",
    "val22": "",
    "val23": "",
    "val24": ""
}