module.exports = {
    "val1": "el campo de nombre debe ser una cadena",
    "val2": "el campo de nombre no debe estar vacio",
    "val3": "el campo de habilitado debe ser booleano",
    "val4": "el campo de descripción debe ser cadena",
    "val5": "el campo de descripción no debe estar vacio",
    "val6": "el campo del identificador de país debe ser entero",
    "val7": "el campo del identificador de región debe ser entero",
    "val8": "el campo del identificador de ciudad debe ser entero",
    "val9": "el campo del identificador de pueblo debe ser entero",
    "val10": "el campo de punto no debe estar vacio",
    "val11": "el tipo del punto debe ser 'Point'",
    "val12": "las coordenadas del punto debe ser un arreglo'",
    "val13": "las coordenadas debe contener los valores [latitud, longitud]'",
    "val14": "las coordenadas debe ser decimales'",
    "val15": "la latitud debe estar un valor entre [-90, 90]'",
    "val16": "la longitud debe estar un valor entre [-180, 180]'",
    "val17": "el campo de perimetro debe tener un valor",
    "val18": "el tipo de perimetro debe ser 'Polygon'",
    "val19": "las coordenadas del perimetro debe ser un arreglo de arreglo de arreglo de decimales",
    "val20": "las coordenadas del perimetro debe contener un poligono simple",
    "val21": "el poligono simple debe ser un arreglo",
    "val22": "el poligono debe tener 4 elementos",
    "val23": "el valor del inicio y final debe ser lo mismo en un poligono",
    "val24": "todos los valores del poligono debe ser diferente (exceptuando el primero y el final)",
    "val25": "el identificador de país debe ser númerico",
    "val26": "el identificador de región debe ser númerico",
    "val27": "el identificador de ciudad debe ser númerico",
    "val27": "el identificador del lugar transitado debe ser númerico"
}